### PR TITLE
v3.0.0 release prep

### PR DESCRIPTION
**Pull request by genebean**
#### Pull Request (PR) description

This PR bumps metadata.json to v3.0.0 and updates the change log in preparation for a new release. The major version bump is a result of the fact that puppet 3.x code and other breaking changes have happened since the last release.

### CODE REVIEW

**Comment by ekohl** [comment]
I added this to the milestone: https://github.com/voxpupuli/puppet-jenkins/milestone/12. What are your thoughts on finishing those issues before the release?

**Comment by genebean** [comment]
I will take a look in just a moment @ekohl

**Comment by genebean** [comment]
Question @ekohl: the test failure seems to be that plugins are being downloaded as root on puppet5 so on the second run they are being chown'ed to jeknins. With the EoL of puppet5, is this something you care about or should the puppet5 tests be removed?

**Comment by ekohl** [comment]
I'd prefer to look at it when https://github.com/voxpupuli/puppet-jenkins/pull/962 is merged. That's currently still running.

**Comment by genebean** [comment]
Per slack, I think the plan is to merge that before this anyhow.

**Comment by genebean** [comment]
Rebased post #962

**Comment by genebean** [comment]
Looking at the current test matrix, should this release also include https://github.com/voxpupuli/puppet-jenkins/pull/1003 that bumps the supported Puppet versions?

**Comment by ekohl** [comment]
I merged #1003.

**Comment by ekohl** [comment]
I need a new release, so I fixed the tests. Now I also want to get this in:
* https://github.com/voxpupuli/puppet-jenkins/pull/1045
* https://github.com/voxpupuli/puppet-jenkins/pull/1055
* https://github.com/voxpupuli/puppet-jenkins/pull/1056

**Comment by ekohl** [comment]
Replaced by https://github.com/voxpupuli/puppet-jenkins/pull/1060

**Pull request closed without merging**
