### PR TITLE
Allow puppetlabs/stdlib 9.x, puppetlabs/java 10.x, puppet/archive 7.x, puppet/zypprepo 5.x, puppet/systemd 6.x

### PR DESCRIPTION
**Pull request by bastelfreak**

### CODE REVIEW

**Review by ekohl — APPROVED** [review]

**Comment by ekohl** [comment]
```
   	Error: Could not install module 'puppetlabs-java' (v10.1.2)
  	  The requested version cannot satisfy one or more of the following installed modules:
  	    puppetlabs-stdlib, installed: 9.3.0, expected: >= 4.13.1 < 10.0.0
```

I may be blind here, but how does that not satisfy the dependency?

**Comment by ekohl** [comment]
I can't explain it now:

```console
$ pry
[1] pry(main)> require 'semantic_puppet'
=> true
[2] pry(main)> SemanticPuppet::VersionRange.parse(">= 4.13.1 < 10.0.0").include?(SemanticPuppet::Version.parse('9.3.0'))
=> true
```

**Comment by evgeni** [comment]
```console
[root@da57947e569e /]# puppet module install puppetlabs-stdlib -v 9.3.0
Notice: Preparing to install into /etc/puppetlabs/code/environments/production/modules ...
Notice: Downloading from https://forgeapi.puppet.com ...
Notice: Installing -- do not interrupt ...
/etc/puppetlabs/code/environments/production/modules
└── puppetlabs-stdlib (v9.3.0)
[root@da57947e569e /]# puppet module install puppetlabs-apt -v 9.1.0
Notice: Preparing to install into /etc/puppetlabs/code/environments/production/modules ...
Notice: Downloading from https://forgeapi.puppet.com ...
Notice: Installing -- do not interrupt ...
/etc/puppetlabs/code/environments/production/modules
└─┬ puppetlabs-apt (v9.1.0)
  └── puppetlabs-stdlib (v9.3.0)
[root@da57947e569e /]# puppet module install puppetlabs-java -v 10.1.2 --verbose
Notice: Preparing to install into /etc/puppetlabs/code/environments/production/modules ...
Notice: Downloading from https://forgeapi.puppet.com ...
Info: Resolving dependencies ...
Info: Preparing to install ...
Notice: Installing -- do not interrupt ...
/etc/puppetlabs/code/environments/production/modules
└─┬ puppetlabs-java (v10.1.2)
  ├── puppet-archive (v7.0.0)
  └── puppetlabs-stdlib (v9.3.0)
```

especially, given this worked…

**Comment by evgeni** [comment]
Ah, but we do not allow archive 7.0… :tableflip:

**Review by evgeni — APPROVED** [review]
ACK'ing Tims changes, in the hope he'll ACK mine

**Comment by evgeni** [comment]
I am kinda sure the failures are unrelated, but my motivation to chase them…

**Review by ekohl — APPROVED** [review]
The plugin failures are certainly a thing this module should address: you need to keep track of all dependencies manually and that changes over time. That causes the tests to fail, quite often.

**Pull request merged**
