### PR TITLE
modulesync 2.7.0 and drop puppet 4

### PR DESCRIPTION
**Pull request by bastelfreak**
modulesync 2.7.0

### CODE REVIEW

**Comment by alexjfisher** [comment]
Does https://github.com/voxpupuli/puppet-jenkins/pull/898 need to be merged first??

**Comment by mmoll** [comment]
What's the status here?

**Comment by bastelfreak** [comment]
@mmoll I am pretty swamped with work at the moment and I don't have enough time here. Are you interested in helping us and and working through the failed tests?

**Comment by rnelson0** [comment]
Can this get a rebase, after the recent metadata changes to ensure it reflects the latest and greatest before troubleshooting any test failures?

**Comment by bastelfreak** [comment]
@rnelson0 I rebased it. I've a feeling that the acceptance tests aren't idempotent :(

**Comment by alexjfisher** [comment]
> I rebased it. I've a feeling that the acceptance tests aren't idempotent :(

FWIW, I restarted the travis build about 5 times today until this went green.

**Comment by mmoll** [comment]
Time for a new forge relase, perhaps? :)

**Comment by Dan33l** [comment]
> I've a feeling that the acceptance tests aren't idempotent :(
Hum ... i suppose you wanted to say that acceptance tests highlight an idempotency issue of puppet code.

**Comment by bastelfreak** [comment]
@Dan33l I've no idea if this is caused by docker or jenkins or puppet.

**Comment by Dan33l** [comment]
@bastelfreak i don't have idea about the root cause and i am not user of module.

But few months ago i update acceptance tests to be able to get a clearer message when it fail.
And what i saw is that same puppet code applied twice can be not idempotent.

**Pull request merged**
