### PR TITLE
Adding SLES to supported platforms

### PR DESCRIPTION
**Pull request by msurato**

### CODE REVIEW

**Comment by othalla** [comment]
@msurato have you tested on Suse servers?
Why not adding some acceptance test for OpenSuSE?

**Comment by msurato** [comment]
I have tested this on Suse, but not OpenSuSE. While they should be fine, I
would think we would want to test first. There is an issue with zypprepo
that is affecting the installation (
https://github.com/voxpupuli/puppet-zypprepo/issues/10), but putting in a
work around with installing the certificate with the RPMKey module (
https://forge.puppet.com/stschulte/rpmkey) is not difficult.

If you want, I can test with OpenSuSE and update the pull request. Please
let me know what you think! Thanks!

**Comment by robpou** [comment]
+1 for this. We are using the module on SLES12 and it works (like on Rhel/Ubuntu OS).
But e.g. we manage the repository ourselves.

**Comment by bastelfreak** [comment]
@robpou thanks for the info and @msurato thanks for the PR!

**Pull request merged**
