### PR TITLE
jenkins_exec type

### PR DESCRIPTION
**Pull request by jhoblitt**
```
  jenkins_exec{ 'job-dsl security':
    script => @(END)
      import jenkins.model.*

      def j = Jenkins.getInstance()
      def jobDsl = j.getDescriptor("javaposse.jobdsl.plugin.GlobalJobDslSecurityConfiguration")
      jobDsl.setUseScriptSecurity(false)
    END
  }
```

### CODE REVIEW

**Comment by jhoblitt** [comment]
@rtyler  I've been sitting on this for over a year as I never got around to writing acceptance tests.  However, it seems to be in a working state.

**Comment by joshuaspence** [comment]
Is this likely to be merged soon? It's exactly what I need and I had already started writing something similar.

**Comment by jhoblitt** [comment]
@joshuaspence I got it as far as basic functionality but haven't had time to sort out the tests.

**Comment by esalberg** [comment]
Instead of jenkins_exec, maybe jenkins_script or jenkins_groovy?

**Comment by jhoblitt** [comment]
The provider started out as a cut'n'paste of an `exec` provider from core puppet and the semantics of the type are intended to be essentially the same.

**Comment by ekohl** [comment]
@jhoblitt any plans to revisit this?

**Comment by jhoblitt** [comment]
@ekohl Nope.

**Pull request closed without merging**
