### PR TITLE
Let bash expand Java arguments

### PR DESCRIPTION
**Pull request by bambriy**
When multiple $JAVA_ARGS are passed in quotation marks, bash passes entire string as a single argument to java command. To make sure options are digested one by one, java options should not be enclosed in quotes.

Re-creating PR hoping that Travis will work this time.

### CODE REVIEW

**Comment by jhoblitt** [comment]
The acceptance tests are failing because the jenkins service isn't starting up.  I don't have time to debug this. Could you try running the beaker locally?

**Comment by bambriy** [comment]
The test has been fixed. Had nothing to do with the change however.

**Comment by degano** [comment]
@bambriy can this be merged now? We could really use it...

**Comment by jhoblitt** [comment]
The PR has commits that are already on master and changes unrelated to the PR description. Could you clean it up?

**Comment by bambriy** [comment]
Rebased and re-shuffled commits. Doesn't look nice on gihub.

Perhaps, it would be neater to re-fork the repo and apply the initial tiny change with new PR. What do you think, @jhoblitt ?

**Comment by krische** [comment]
This still appears to be a problem. Specifying multiple JAVA_ARGS does not work.

**Pull request closed without merging**
