### PR TITLE
Fix code ordering for ubuntu 18.04 and puppet6

### PR DESCRIPTION
**Pull request by asifbadkarma**
#### This Pull Request (PR) fixes the following issues

Fixes : #920

### CODE REVIEW

**Comment by gittygoo** [comment]
Can this be merged? seems to work for me

**Comment by ekohl** [comment]
This doesn't look correct to me. My impression is that you first need to stop the old sysvinit service and then you can define the new service. Otherwise systemd will just stop the systemd based service but leave sysvinit around.

**Comment by asifbadkarma** [comment]
Anything I need to do to improve this and maybe get it merged ?

**Comment by ekohl** [comment]
I think your solution is incorrect. Once the systemd unit file is in place, systemd will use that to stop the service. However, the entire goal of the transition is to stop the service using the sysvinit script before removing that script. Only then can you start to set up systemd based services. While your change may appear to work, I don't think the transition has any effect anymore.

It also breaks the tests.

**Comment by ekohl** [comment]
Closing for inactivity.

**Pull request closed without merging**
