### PR TITLE
Handle arguments with spaces

### LINKED ISSUE #927: CSP Support
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.10
- Ruby: 2.0.0p648
- Distribution: CentOS 7.x
- Module version: latest master

## How to reproduce (e.g Puppet code you use)

Set the Java option in your yaml manifest like this:
```
jenkins::config_hash
  'JENKINS_JAVA_OPTIONS':
    value: |
        -Dhudson.model.DirectoryBrowserSupport.CSP="sandbox allow-same-origin allow-scripts allow-popups; default-src 'none'; img-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'; connect-src *;"
```

## What are you seeing

```
Error: Could not find or load main class allow-same-origin
```

## What behaviour did you expect instead

Jenkins clean start.

## Output log

N/A

## Any additional information you'd like to impart

The java command line seems has an issue with system properties and spaces within their values.

### PR DESCRIPTION
**Pull request by julianxhokaxhiu**
#### Pull Request (PR) description
Allow Java System Properties that may contain spaces as options parameters, like -Dhudson.model.DirectoryBrowserSupport.CSP="sandbox allow-same-origin"

#### This Pull Request (PR) fixes the following issues
Fixes #927

### CODE REVIEW

**Comment by ekohl** [comment]
Acceptance tests are failing. Not sure if this is also the case in master right now.

**Comment by julianxhokaxhiu** [comment]
@ekohl I noticed that as well, but the errors do not look like anything related to the patch I did. Also because the patch itself can be proofed only on a running Jenkins. Unless the CI does that but I didn't found any trace of this task.

Would be good although to have a double check on master too. The interesting part is that 4 jobs out of 8 were successful, which means something is wrong in the CI scripts probably.

**Comment by julianxhokaxhiu** [comment]
Testing it with @jandro we found out that actually there was one more syntax issue that was preventing Jenkins to start successfully. I implemented it already and push the new commit.

Before:
```
PARAMS+=("-jar $JENKINS_WAR")
```
After:
```
PARAMS+=("-jar")
PARAMS+=("$JENKINS_WAR")
```

**Comment by julianxhokaxhiu** [comment]
Fixed another "broken" behavior although visually visibile, bash didn't complain, nor the java process.

I introduced a new Bash function named `add_jenkins_java_options` to slice the JENKINS_JAVA_OPTIONS safely and add each option given as a single item in the array, otherwise bash would evaluate it wrongly and give it as a whole string ( confusing java on how to interpret the option, seeing it as a single one ).

**Comment by ekohl** [comment]
Currently I'm lacking time and green tests would make me much more confident in merging it. A separate PR to master to get tests green would be sufficient for me to hit the big green merge button.

**Comment by julianxhokaxhiu** [comment]
I would have to understand where the issue is there but I'll try to find some time to do it. I'll let you know when I'll open a PR.

**Comment by julianxhokaxhiu** [comment]
@ekohl any update on the pipeline? is it fixed now? Can you retrigger another build please?

**Comment by julianxhokaxhiu** [comment]
Hi, It seems we got stuck again on this PR. Is there still an interest on this? Has this been fixed in the meanwhile?

**Comment by julianxhokaxhiu** [comment]
~1y has passed. Are you interested or shall I close the PR?

**Comment by kenyon** [comment]
> ~1y has passed. Are you interested or shall I close the PR?

@julianxhokaxhiu if you rebase on the current master, that will let us see the current state of the tests.

**Comment by julianxhokaxhiu** [comment]
Done :) Let me know if anything else is required on my own end. Thank you!

**Comment by ekohl** [comment]
Made obsolete by #1035

**Pull request closed without merging**
