### PR TITLE
enables the use of a template for the plugin configuration

### PR DESCRIPTION
**Pull request by witjoh**
Installing plugins using hiera and the jenkins::plugins class, it is impossible to generate the config_content using a template.  With this addition, it becomes a piece of cake.

### CODE REVIEW

**Comment by jhoblitt** [comment]
What is the use case for this feature that isn't covered by `config_content  => template(...)`?  Also, puppet 4.x users may want to use `epp()`.

**Comment by witjoh** [comment]
about the epp, thats indeed a good point, will add support for it. (just need to read a bit, since we are still on 3.x).

when one puts jenkins::plugin_hash in hiera, it is impossible to get the content from a template into the config_content.  We could indeed call the plugin resource for those plugins that need a template configuration, but then we have to keep the configuration in two places, in hiera and in our jenkins profile. 
Keeping everything in one place is what we prefer.
See also this ticket :
https://tickets.puppetlabs.com/browse/HI-295

Will update this PR with epp support today.

**Comment by witjoh** [comment]
* added support for both erb and epp
* added also rspec testing

**Comment by witjoh** [comment]
@jhoblitt Any change to have a quick review ?

**Comment by sdiepend** [comment]
@jhoblitt @rtyler @witjoh Any updates on this? I'm also interested in this pull request.

**Comment by jhoblitt** [comment]
Haven't had any mental bandwidth.  I'm surprised that the `epp()` function call isn't causing a problem with puppet 3.8 -- anyone have an explanation?

**Comment by witjoh** [comment]
@jhoblitt 
Did a little test with 3.8.5, and I get the following error : 
Error: epp() is only available when parser/evaluator future is in effect at /home/vagrant/modules/epptest/manifests/init.pp:7 on node slave.vagrant.com

[vagrant@slave ~]$ puppet agent --configprint parser
current
[vagrant@slave ~]$ puppet apply --modulepath modules modules/epptest/examples/init.pp  --parser future does work as expected.

**Comment by witjoh** [comment]
@jhoblitt ping ?

**Comment by witjoh** [comment]
@jhoblitt :  is this still in the running ? time for a rebase ?

**Comment by jhoblitt** [comment]
@witjoh Could you try rebasing this PR to see if the test will pass?  The acceptance tests are now reliable on the master branch.

**Comment by bastelfreak** [comment]
Hello. I'm going to close this PR due to inactivity. Please reopen and rebase it if you're still interested in it.

**Pull request closed without merging**
