### PR TITLE
Add spec tests for jenkins::slave::tunnel parameter

### PR DESCRIPTION
**Pull request by ghoneycutt**

### CODE REVIEW

**Comment by ghoneycutt** [comment]
Adds on to #841

**Comment by alexjfisher** [comment]
@ghoneycutt Do you mean https://github.com/voxpupuli/puppet-jenkins/pull/840 ?

**Comment by ghoneycutt** [comment]
@alexjfisher yes, thanks!

**Comment by alexjfisher** [comment]
@ghoneycutt Would you mind if https://github.com/voxpupuli/puppet-jenkins/pull/843 went in first and then rebasing and checking the rubocop violations that PR fixed haven't been reintroduced?

**Comment by jhoblitt** [comment]
It needs to be rebased to be a FF merge anyways.

**Comment by alexjfisher** [comment]
@jhoblitt Would you prefer all merges to be fast-forward only?  I think this can be configured (we don't *usually* enforce that, but I think we could trial it on this project if you wanted).

**Comment by jhoblitt** [comment]
@alexjfisher I've never been a stickler about requiring general PRs to be a FF merge, although, I always ensure that my PRs are.

**Comment by jhoblitt** [comment]
@ghoneycutt Could you rebase?

**Comment by ekohl** [comment]
Closing for inactivity.

**Pull request closed without merging**
