### PR TITLE
puppet/archive: allow 5.x

### PR DESCRIPTION
**Pull request by bastelfreak**

### CODE REVIEW

**Review by ekohl — COMMENTED** [review]
Any particular reason you're moving the block instead of replacing it inline?

**Comment by bastelfreak** [comment]
I was hoping that this causes the puppet module tool to resolve the dependencies, but that doesn't work :(

**Comment by bastelfreak** [comment]
This depends on https://github.com/puppetlabs/puppetlabs-java/pull/476

**Comment by saz** [comment]
@bastelfreak puppetlabs/puppetlabs-java#476 is merged now

**Pull request merged**
