### PR TITLE
allow puppetlabs/java < 7.0.0

### PR DESCRIPTION
**Pull request by saz**

### CODE REVIEW

**Review by kenyon — APPROVED** [review]

**Comment by saz** [comment]
Is there anything I can do to get this merged? Failing tests seem to be unrelated to my change.

**Comment by ekohl** [comment]
I opened https://github.com/voxpupuli/puppet-jenkins/pull/995 which should lead to green unit tests.

**Comment by ekohl** [comment]
Please rebase

**Comment by saz** [comment]
Rebased

**Comment by saz** [comment]
@ekohl Tests are still failing :(

**Review by ekohl — APPROVED** [review]
They're failing in the same way on master. I haven't been able to track down why the acceptance tests pass in my vagrant-libvirt VM but fail on CentOS 7 on Docker. https://github.com/voxpupuli/puppet-jenkins/issues/993 is a good candidate but I haven't had time to look into it.

Merging now.

**Comment by saz** [comment]
Thanks for merging!

**Pull request merged**
