### PR TITLE
More Rubocop fixes

### PR DESCRIPTION
**Pull request by alexjfisher**
50 More autofix style rubocop fixes.

For reference, the following list now all pass.
```
rubocop -D -S -E --only rubocop -D -S -E --only Layout/SpaceAroundBlockParameters,Layout/EmptyLinesAroundBlockBody,Style/StringLiterals,Layout/SpaceAroundOperators,Style/TrailingCommaInLiteral,Layout/SpaceAfterComma,Layout/LeadingCommentSpace,Layout/CaseIndentation,Style/RedundantReturn,Style/CollectionMethods,Style/RedundantParentheses,Style/AndOr,Layout/AlignHash,Style/BlockDelimiters,Style/NegatedIf,Style/MultilineIfThen,Lint/UnusedBlockArgument,Layout/ExtraSpacing,Style/ParenthesesAroundCondition,Style/IfUnlessModifier,RSpec/ExampleWording,Style/ParenthesesAroundCondition,Layout/EmptyLines,Style/MethodCallWithoutArgsParentheses,Layout/SpaceInsideBlockBraces,Layout/SpaceInsideHashLiteralBraces,Style/TrailingCommaInArguments,Layout/SpaceInsideBrackets,Layout/EmptyLinesAroundAccessModifier,Style/Proc,Layout/SpaceInsideRangeLiteral,Layout/TrailingBlankLines,Layout/SpaceInsidePercentLiteralDelimiters,Style/CharacterLiteral,Layout/EmptyLinesAroundMethodBody,Layout/SpaceBeforeBlockBraces,Layout/AlignArray,Layout/IndentArray,Style/HashSyntax,Layout/EmptyLineBetweenDefs,Lint/DeprecatedClassMethods,Layout/SpaceInsideParens,Style/BracesAroundHashParameters,RSpec/ImplicitExpect,Layout/AlignParameters,Style/YodaCondition,Style/Encoding,Layout/IndentationWidth,Layout/ElseAlignment,Style/ParenthesesAroundCondition,Style/ConditionalAssignment,Style/UnlessElse,Style/SignalException,Style/FormatString,Style/RedundantSelf,Performance/StringReplacement,Layout/AccessModifierIndentation,Lint/UnusedMethodArgument,Layout/TrailingWhitespace,Style/RescueModifier,Style/PercentLiteralDelimiters,Style/InverseMethods,Style/MutableConstant,Style/UnneededInterpolation,Style/ParallelAssignment,Style/NegatedIf,Style/Semicolon,Style/SingleLineMethods,Style/SelfAssignment,Style/NilComparison,Style/NegatedWhile,Style/ZeroLengthPredicate,Performance/RedundantMerge,Style/RedundantBegin,Performance/RedundantBlockCall,RSpec/DescribedClass,Layout/DotPosition
```

### CODE REVIEW

**Comment by jhoblitt** [comment]
I personally don't like removing `TrailingCommaInArguments` as it often results in an extra line in diffs (to add the trailing comment) when parameters are changed. That said I will go along with others preferences.

**Comment by alexjfisher** [comment]
@jhoblitt I think that's a valid argument.  But... we try to use the same .rubocop.yml config file in all Vox Pupuli modules.  So if we change it, I think we should do it in *all* modules.

ping @bastelfreak

**Comment by alexjfisher** [comment]
Looks like the tests might be failing for an actual reason, (instead of random issues with the acceptance tests).  I'll have a dig into it tomorrow.  It's not unheard of for rubocop autofix to break stuff.

**Comment by bastelfreak** [comment]
@jhoblitt I share your opinion. Would you mind proposing this to https://github.com/voxpupuli/modulesync_config/blob/master/moduleroot/.rubocop.yml.erb? That is the template that gets synced to all repos. We should there discuss if we change it (maybe somebody is against it).

**Comment by alexjfisher** [comment]
I think I found the issue in the Style/SignalException commit.  I've amended it.  Fingers crossed the build will pass now.

**Pull request merged**
