### PR TITLE
modulesync 1.7.0

### PR DESCRIPTION
**Pull request by bastelfreak**

### CODE REVIEW

**Comment by jhoblitt** [comment]
There is a lot of churn due to the auto-magic reformatting.  Perhaps it would be better to split that off as a separate PR?

**Comment by rnelson0** [comment]
I don't know that there is a good way to separate these changes out without it being a lot to check, and worse, it would prevent builds from being green on all but the last commit. The changes do look okay, but the tests do need some fixing, starting with renaming a few files.

**Comment by bastelfreak** [comment]
parts of this are in https://github.com/voxpupuli/puppet-jenkins/pull/834

**Comment by bastelfreak** [comment]
parts of this are in https://github.com/voxpupuli/puppet-jenkins/pull/832

**Comment by bastelfreak** [comment]
parts of this are in https://github.com/voxpupuli/puppet-jenkins/pull/831

**Comment by bastelfreak** [comment]
parts of this are in https://github.com/voxpupuli/puppet-jenkins/pull/830

**Comment by rnelson0** [comment]
Closing since the other PRs cover it.

**Pull request closed without merging**
